using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Capstone.Web.Models
{
    /// <summary>
    /// View model for actions based on CRUD functionality of the TB_Capstone_ROLE table
    /// </summary>
    public class RoleViewModel
    {
        /// <summary>
        /// Autogenerated index value, not for display to screen
        /// </summary>
        public int RoleID { get; set; }

        public string RoleTitle { get; set; }

        public string Description { get; set; }

        public DateTime ActivationDate { get; set; }

    }
}
